spring:
  application:
    name: eureka

info.app:
  name: eureka
  description: Service discovery service

server:
  port: ${PORT:8762}

eureka:
#  instance:
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #http://stackoverflow.com/questions/33150981/eurekas-self-preservation-mode-never-recovers
    renewalPercentThreshold: 0.49
#    enableSelfPreservation: false
    registrySyncRetries: 0

logging:
  level:
    com.netflix: 'WARN'
    org.springframework: 'WARN'
    com.netflix.eureka.PeerAwareInstanceRegistry: 'ERROR'

security:
  user:
    password: 's3cr3tS'


